import 'dart:io';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../models/chef_models/food_model.dart';
import '../../services/chef/food_service.dart';

class AddFoodScreen extends StatefulWidget {
  const AddFoodScreen({Key? key}) : super(key: key);

  @override
  State<AddFoodScreen> createState() => _AddFoodScreenState();
}

class _AddFoodScreenState extends State<AddFoodScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descController = TextEditingController();
  final _priceController = TextEditingController();

  XFile? _selectedImage;
  String? _category;
  bool _isAvailable = true;

  final List<String> _categories = [
    'Starters',
    'Main Course',
    'Drinks',
    'Desserts',
  ];

  final ImagePicker _picker = ImagePicker();

  Future<void> _pickImage() async {
    final XFile? image = await _picker.pickImage(source: ImageSource.gallery);
    if (image != null) {
      setState(() {
        _selectedImage = image;
      });
    }
  }

  Future<String> _uploadImage() async {
    final imageName = 'food_${DateTime.now().millisecondsSinceEpoch}.${_selectedImage!.path.split('.').last}';
    final imagePath = 'foods/$imageName';
    final supabase = Supabase.instance.client;

    final bytes = await _selectedImage!.readAsBytes();

    await supabase.storage.from('food-images').uploadBinary(
      imagePath,
      bytes,
      fileOptions: const FileOptions(cacheControl: '3600', upsert: false),
    );

    return supabase.storage.from('food-images').getPublicUrl(imagePath);
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;
    if (_selectedImage == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text("Please select an image")),
      );
      return;
    }

    try {
      final imageUrl = await _uploadImage();
      final userId = Supabase.instance.client.auth.currentUser?.id;

      if (userId == null) {
        throw Exception("User not logged in");
      }

      final newFood = FoodModel(
        id: '', // generated by backend
        chefId: userId,
        restaurantId: '', // Fill if applicable
        title: _titleController.text.trim(),
        description: _descController.text.trim(),
        price: double.parse(_priceController.text.trim()),
        imageUrl: imageUrl,
        isAvailable: _isAvailable,
        category: _category!,
        createdAt: DateTime.now(),
      );

      await FoodService().addFood(newFood);
      if (mounted) {
        Navigator.pop(context);
      }
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text("Failed to add food: $e")),
      );
    }
  }

  @override
  void dispose() {
    _titleController.dispose();
    _descController.dispose();
    _priceController.dispose();
    super.dispose();
  }

  Widget _buildImagePreview() {
    if (_selectedImage == null) {
      return Container(
        height: 150,
        width: double.infinity,
        color: Colors.grey[300],
        child: const Icon(Icons.add_a_photo, size: 50, color: Colors.deepOrange),
      );
    } else {
      return kIsWeb
          ? Image.network(_selectedImage!.path, height: 150, fit: BoxFit.cover)
          : Image.file(File(_selectedImage!.path), height: 150, fit: BoxFit.cover);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Add Food")),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              GestureDetector(
                onTap: _pickImage,
                child: _buildImagePreview(),
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _titleController,
                decoration: const InputDecoration(labelText: "Title"),
                validator: (value) => value!.isEmpty ? "Enter title" : null,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _descController,
                decoration: const InputDecoration(labelText: "Description"),
                validator: (value) => value!.isEmpty ? "Enter description" : null,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _priceController,
                decoration: const InputDecoration(labelText: "Price"),
                keyboardType: TextInputType.number,
                validator: (value) => value!.isEmpty ? "Enter price" : null,
              ),
              const SizedBox(height: 16),
              DropdownButtonFormField<String>(
                value: _category,
                hint: const Text("Select Category"),
                items: _categories
                    .map((cat) => DropdownMenuItem(value: cat, child: Text(cat)))
                    .toList(),
                onChanged: (val) => setState(() => _category = val),
                validator: (val) => val == null ? 'Please select category' : null,
              ),
              const SizedBox(height: 16),
              SwitchListTile(
                activeColor: Colors.deepOrange,
                title: const Text("Is Available"),
                value: _isAvailable,
                onChanged: (val) => setState(() => _isAvailable = val),
              ),
              const SizedBox(height: 24),
              ElevatedButton(
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.deepOrange,
                  foregroundColor: Colors.white,
                  minimumSize: const Size(double.infinity, 50),
                ),
                onPressed: _submit,
                child: const Text("Add Food"),
              )
            ],
          ),
        ),
      ),
    );
  }
}
